"""Backward-compatible alias package for Spatial LTM + MANN reconstruction.

Re-exports the canonical ``mnemonic_cortex.ltm`` public API so older import paths
keep working without duplicating implementation modules.
"""
from .. import (
    DEFAULT_CGMN_DEPTH_CHART,
    DEFAULT_HG_DEPTH_CHART,
    DEFAULT_MANN_DEPTH_CHART,
    DEFAULT_SPATIAL_DEPTH_CHART,
    ContextToken,
    DepthRouter,
    DualTransformerPolicy,
    EnhancedSpatialMnemonicCortex,
    GeometryKeyProjector,
    GeometryMemoryBank,
    LTMReadResult,
    LTMSubsystem,
    MANNReasoner,
    ReasoningStack,
    SensoryContextBuffer,
    SensoryToken,
    SharedValueStore,
    SharedWriteTrace,
    SpatialLtmMannConfig,
    TransformerBlock,
    TransformerStack,
    TripleHybridLTM,
    WorkingMemory,
    default_config,
    exp_map,
    frechet_mean,
    log_map,
    metric_distance,
    parallel_transport,
)

__all__ = [
    "SpatialLtmMannConfig",
    "default_config",
    "DualTransformerPolicy",
    "DEFAULT_MANN_DEPTH_CHART",
    "DEFAULT_HG_DEPTH_CHART",
    "DEFAULT_CGMN_DEPTH_CHART",
    "DEFAULT_SPATIAL_DEPTH_CHART",
    "SharedValueStore",
    "SharedWriteTrace",
    "DepthRouter",
    "GeometryKeyProjector",
    "GeometryMemoryBank",
    "LTMReadResult",
    "LTMSubsystem",
    "TripleHybridLTM",
    "MANNReasoner",
    "WorkingMemory",
    "SensoryContextBuffer",
    "SensoryToken",
    "ContextToken",
    "EnhancedSpatialMnemonicCortex",
    "TransformerBlock",
    "TransformerStack",
    "ReasoningStack",
    "metric_distance",
    "log_map",
    "exp_map",
    "parallel_transport",
    "frechet_mean",
]
